// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniEats.Domain.Data;

#nullable disable

namespace UniEats.Domain.Migrations
{
    [DbContext(typeof(UniEatsDbContext))]
    partial class UniEatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniEats.Domain.Entities.MealListing", b =>
                {
                    b.Property<Guid>("MealListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Allergens")
                        .HasColumnType("text");

                    b.Property<Guid>("CookId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Ingredients")
                        .HasColumnType("text");

                    b.Property<decimal?>("PickupLat")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PickupLng")
                        .HasColumnType("numeric");

                    b.Property<string>("PickupLocationText")
                        .HasColumnType("text");

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("ServingsAvailable")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("MealListingId");

                    b.HasIndex("CookId");

                    b.ToTable("MealListings");
                });

            modelBuilder.Entity("UniEats.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BuyerFeeCents")
                        .HasColumnType("integer");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CookId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MakerFeeCents")
                        .HasColumnType("integer");

                    b.Property<Guid>("MealListingId")
                        .HasColumnType("uuid");

                    b.Property<int>("MealPriceCents")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPaidCents")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("MealListingId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("UniEats.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<Guid>("CookId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.HasKey("ReviewId");

                    b.HasIndex("OrderId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("UniEats.Domain.Entities.StrikeEvent", b =>
                {
                    b.Property<Guid>("StrikeEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CookId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StrikeEventId");

                    b.HasIndex("CookId");

                    b.HasIndex("OrderId");

                    b.ToTable("StrikeEvents");
                });

            modelBuilder.Entity("UniEats.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvgRating")
                        .HasColumnType("numeric");

                    b.Property<string>("Campus")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBannedFromPosting")
                        .HasColumnType("boolean");

                    b.Property<int>("StrikeCount")
                        .HasColumnType("integer");

                    b.Property<string>("University")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_User_Email_EduAu", "\"Email\" LIKE '%.edu.au'");
                        });
                });

            modelBuilder.Entity("UniEats.Domain.Entities.MealListing", b =>
                {
                    b.HasOne("UniEats.Domain.Entities.User", "Cook")
                        .WithMany("MealListings")
                        .HasForeignKey("CookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cook");
                });

            modelBuilder.Entity("UniEats.Domain.Entities.Order", b =>
                {
                    b.HasOne("UniEats.Domain.Entities.User", "Buyer")
                        .WithMany("Orders")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniEats.Domain.Entities.MealListing", "MealListing")
                        .WithMany()
                        .HasForeignKey("MealListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("MealListing");
                });

            modelBuilder.Entity("UniEats.Domain.Entities.Review", b =>
                {
                    b.HasOne("UniEats.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("UniEats.Domain.Entities.StrikeEvent", b =>
                {
                    b.HasOne("UniEats.Domain.Entities.User", "Cook")
                        .WithMany()
                        .HasForeignKey("CookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniEats.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cook");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("UniEats.Domain.Entities.User", b =>
                {
                    b.Navigation("MealListings");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
